version: '3.9'

services:
  httpServerGin:
    build:
      context: .
      dockerfile: Dockerfile
      target: gin-builder
    ports:
      - "8081:8080"
    container_name: http_server_gin

  httpServer:
    build:
      context: .
      dockerfile: Dockerfile
      target: standard-builder
    ports:
      - "8082:8080"
    container_name: http_server_standard
